apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: man-nginx-1
  name: man-nginx-1
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: man-nginx-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: man-nginx-1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
