apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: man-nginx-1
  name: man-nginx-1
spec:
  replicas: 9
  selector:
    matchLabels:
      app: man-nginx-1
  strategy: {}
  template:
    metadata:
      labels:
        app: man-nginx-1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
