apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: man-nginx
  name: man-nginx
spec:
  replicas: 100
  selector:
    matchLabels:
      app: man-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: man-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
