apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: deployer-global
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: default
roleRef:
  kind: ClusterRole
  name: deployer-cluster-role
  apiGroup: rbac.authorization.k8s.io