apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: deployer
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
  # - apiGroups: [""]
  #   resources: ["pods", "pods/exec"]
  #   verbs: ["get", "list", "delete", "patch", "create"]
  # - apiGroups: ["extensions", "apps"]
  #   resources: ["deployments", "deployments/scale"]
  #   verbs: ["get", "list", "delete", "patch", "create"]