apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-github-actions
subjects:
  - kind: ServiceAccount
    name: github-actions
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io