apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-02-10T10:23:18Z"
  name: github-actions
  namespace: default
  resourceVersion: "19006"
  uid: 758c63ea-9c4b-4918-920f-5fbd20025799
secrets:
- name: github-actions-token-zmh4h
