on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    
    - name: Config kubectl
      run: |
        kubectl config set-cluster proen-kubeops --server ${{ secrets.KUBE_CLUSTER_SERVER }} --embed-certs --certificate-authority <(echo "${{ secrets.KUBE_CLUSTER_CERTIFICATE_AUTHORITY_DATA }}")
        kubectl config set-credentials github-actions --token=${{ secrets.ACTIONS_SA_TOKEN }}
        kubectl config set-context github-actions@proen-kubeops --user=github-actions --cluster=proen-kubeops
        kubectl config use-context github-actions@proen-kubeops

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Install Krane
      run: gem install krane

    - name: Deploy with krane
      run: krane deploy default kubernetes-admin@kubernetes -f ./deployments/ --no-prune

    # - name: Test
    #   run: |
    #     cat ~/.kube/config
        
  #   # - name: Test KubeCtl
  #   #   run: |
  #   #     kubectl get deployments

  # build:
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Test KubeCtl
  #     run: |
  #       kubectl get deployments

