on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Set service account context
      run: |
        kubectl config set-cluster proen-kubeops --server ${{ secrets.KUBE_CLUSTER_SERVER }} --embed-certs --certificate-authority <(echo "${{ secrets.KUBE_CLUSTER_CERTIFICATE_AUTHORITY_DATA }}")
        kubectl config set-credentials github-actions --token=${{ secrets.ACTIONS_SA_TOKEN }}
        kubectl config set-context github-actions@proen-kubeops --user=github-actions --cluster=proen-kubeops
        kubectl config use-context github-actions@proen-kubeops
        
    - name: Test KubeCtl
      run: |
        kubectl get deployments


