name: Deploy to Kubenertes Cluster

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master

    - name: Install kubectl v.1.22.4
      run: |
        curl -LO "https://dl.k8s.io/release/v1.22.4/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        rm /usr/local/bin/kubectl
        mv ./kubectl /usr/local/bin/

    - name: Config kubectl
      run: |
        kubectl config set-cluster kubernetes --server ${{ secrets.KUBE_CLUSTER_SERVER }} \
          --embed-certs --certificate-authority <(echo "${{ secrets.KUBE_CLUSTER_CERTIFICATE_AUTHORITY_DATA }}")
        kubectl config set-credentials github-actions --token=${{ secrets.ACTIONS_SA_TOKEN }}
        kubectl config set-context github-actions@kubernetes --user=github-actions --cluster=kubernetes
        kubectl config use-context github-actions@kubernetes
        kubectl version

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true

    - name: Install Krane
      run: gem install krane

    - name: Deploy with krane
      run: krane deploy production github-actions@kubernetes -f ./manifests/deployments/ --no-prune
